- name: Build & Deploy Docker  Container
  hosts: dockerservers
  gather_facts: false
  remote_user: root
  tasks:
    - name: Copy the files to remote server
      become: true
      copy:
        src: /var/lib/jenkins/workspaces/ansible-jenkins-pipeline
        dest: ~/project
        remote_src: true

    - name: Building Docker Image
      docker_image:
        name: portfolio:latest
        build:
          path: ~/project
        state: present

    - name: Creating The condainer
      docker_container:
        name: portfolio
        image: portfolio:latest
        ports:
          - "80:80"
        state: started
