- name: Build & Deploy Docker Container
  hosts: dockerservers
  gather_facts: false
  remote_user: root
  tasks:
    - name: Stopping Docker Container
      docker_container:
        name: portfolio-container
        image: portfolio:latest
        state: stopped

    - name: Removing Docker Container
      docker_container:
        name: portfolio-container
        image: portfolio:latest
        state: absent

    - name: Removing  Docker Image
      docker_image:
        name: portfolio:latest
        state: absent

    - name: Building Docker Image
      docker_image:
        name: portfolio:latest
        source: build
        build:
          path: ~/project/
        state: present

    - name: Creating The Container
      docker_container:
        name: portfolio-container
        image: portfolio:latest
        ports:
          - "80:80"
        state: started
